Change PipeVal command because the interface was changed
uclahs-cds/pipeline-Nextflow-module pull request #43
Opened 2024-06-06 12:16 UTC by zhuchcn

PipeVal was updated to have the top-level command `pipeval`, but the module wasn't updated.

- [X] I have read the [code review guidelines](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [X] The name of the branch is meaningful and well formatted following the [standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List), using \[AD_username (or 5 letters of AD if AD is too long)-\[brief_description_of_branch].

- [X] I have set up or verified the branch protection rule following the [github standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

- [ ] I have added my name to the contributors listings in the
``metadata.yaml`` and the ``manifest`` block in the `nextflow.config` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

- [X] I have added the changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

- [X] I have updated the version number in the `metadata.yaml` and `manifest` block of the `nextflow.config` file following [semver](https://semver.org/), or the version number has already been updated. (*Leave it unchecked if you are unsure about new version number and discuss it with the infrastructure team in this PR.*)

- [X] I have tested the pipeline on at least one A-mini sample.

Closes #...

## Testing Results

- Case 1
    - sample:    
    - input csv: 
    - config:    
    - output:    
- Case 2
    - sample:    
    - input csv: 
    - config:    
    - output:

2024-06-07 16:46 UTC, nwiltsie requested changes
The changes seem fine, but I want to walk through the logic of why this hasn't been an issue before now.

The `pipeval` entrypoint was added 7 months ago with https://github.com/uclahs-cds/package-PipeVal/pull/88. That change was first released in https://github.com/uclahs-cds/package-PipeVal/releases/tag/v5.0.0-rc.1. Grepping for the string `pipeval_version =` across all of our projects and pipelines, `4.0.0` is the highest version currently in use.

Merging this this change will force all of those repositories to simultaneously upgrade the `pipeval_version` to a release candidate (there is currently no `v5.0.0`).

For this kind of major interface change I think we need to support using both the old and new versions. One way to do that would be to add an `if command -v pipeval &> /dev/null` conditional:

**testscript.sh**
```bash
#!/bin/bash

set -euo pipefail

if command -v pipeval &> /dev/null; then
    echo "Updated version!"
else
    echo "OLD version"
fi
```

**Dockerfile**
```dockerfile
ARG PIPEVAL_VERSION
FROM ghcr.io/uclahs-cds/pipeval:${PIPEVAL_VERSION}

COPY testscript.sh /tmp/

ENTRYPOINT ["/tmp/testscript.sh"]
```

```console
$ docker run -it $(docker build -q . --build-arg="PIPEVAL_VERSION=4.0.0")
OLD version
$ docker run -it $(docker build -q . --build-arg="PIPEVAL_VERSION=5.0.0-rc.3")
Updated version!

2024-06-07 16:52 UTC, nwiltsie requested changes

2024-06-07 19:58 UTC, yashpatel6 reviewed
I think @nwiltsie's suggestion to support both versions makes sense to prevent mass breaking of pipelines due to the interface change.

2024-06-07 19:58 UTC, yashpatel6 commented on modules/PipeVal/generate-checksum/main.nf
**suggestion (blocking):** the default version in the accompanying `functions.nf` should also be updated for this and the validation module

2024-06-14 19:15 UTC, yashpatel6 commented
Updated and tested here: `/hot/software/pipeline/pipeline-Nextflow-module/Nextflow/development/unreleased/czhu-fix-pipeval` with both versions working with the same module

2024-06-14 19:17 UTC, nwiltsie approved these changes
Looks great!

2024-06-14 20:00 UTC, merged